### ISSUE TITLE
No file error

### ISSUE THREAD

**Issue by Zumbalamambo** [AaltoVision/hscnet#1]
It is throwing the following error while trying to train with kings college dataset. There is no file called "centers.npy"

```
envs/slam/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/Cambridge/KingsCollege/centers.npy'
```

**Comment by LLXXTTT** [comment]
Hi,

This file should be available in the provided [data package](https://drive.google.com/file/d/1VnUbxYB6Akh8crv06lvDK60qg4lHXcRc/view?usp=sharing).
