### ISSUE TITLE
Question about datasets

### ISSUE THREAD

**Issue by LZL-CS** [AaltoVision/hscnet#3]
Hi,
Thanks for sharing your great work. 

May I know the mean of "centers.npy", "translation.txt" of each scene and the mean of "sensorTrans.txt".

Thanks!

**Comment by LLXXTTT** [comment]
Hi,

Thanks for your interest in our work. The sensorTrans.txt file contains the extrinsics for aligning the depth and the RGB frames and the translation.txt file contains the XYZ values of the center of the scene. More details can be found in the [DSAC documentation](https://github.com/cvlab-dresden/DSAC/blob/master/documentation.pdf). In our work, each scene is split into several subscenes and the centers.npy contains the XYZ values of the subscene centers, more details can be found in the paper.

**Comment by LZL-CS** [comment]
> Hi,
> 
> Thanks for your interest in our work. The sensorTrans.txt file contains the extrinsics for aligning the depth and the RGB frames and the translation.txt file contains the XYZ values of the center of the scene. More details can be found in the [DSAC documentation](https://github.com/cvlab-dresden/DSAC/blob/master/documentation.pdf). In our work, each scene is split into several subscenes and the centers.npy contains the XYZ values of the subscene centers, more details can be found in the paper.

Hi,
Thanks for your reply. 
When I go deep into your code about the depth process, I canot figure out the code as below:
![image](https://user-images.githubusercontent.com/54640259/130987884-fcbbbdc9-7774-4b50-aec4-068dc14d7dce.png)

Could you give me some suggestions about it?

**Comment by LLXXTTT** [comment]
Here we project the 2D pixel coordinates back into 3D camera coordinates in the opengl camera coordinate system given the depth values and the camera intrinsics.
